# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Candela < Formula
  desc "Local LLM observability proxy — traces, costs, and budgets for AI-powered dev tools"
  homepage "https://github.com/candelahq/candela"
  version "0.3.3"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/candelahq/candela/releases/download/v0.3.3/candela_0.3.3_Darwin_universal.tar.gz"
    sha256 "492e873ee5c465000feb20d6047537a8e245c49865dd6af0ff1764636b36f510"

    define_method(:install) do
      bin.install "candela"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/candelahq/candela/releases/download/v0.3.3/candela_0.3.3_Linux_amd64.tar.gz"
      sha256 "6fa48fcea74cdeb73f5e1894649d6b32a46ecc35cce3be40e1ec6f78ffe4c8b5"
      define_method(:install) do
        bin.install "candela"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/candelahq/candela/releases/download/v0.3.3/candela_0.3.3_Linux_arm64.tar.gz"
      sha256 "b499f1b531a5e5d23e8bad1308a0872b5ce883d0a809a94b4a875d65e9930bf4"
      define_method(:install) do
        bin.install "candela"
      end
    end
  end

  def caveats
    <<~EOS
      To get started, create a config file:

        mkdir -p ~/.config/candela
        cat > ~/.config/candela/config.yaml <<EOF
        port: 8181
        providers:
          - name: google
            models: ["gemini-2.5-pro", "gemini-2.5-flash"]
        vertex_ai:
          project: YOUR_GCP_PROJECT
          region: us-central1
        EOF

      Then run:
        candela start          # background daemon
        candela status         # check running state
        candela run            # foreground (debug)

      Management UI: http://127.0.0.1:8181/_local/

      Or as a login service:
        brew services start candela
    EOS
  end

  service do
    run [opt_bin/"candela", "run"]
    keep_alive true
    log_path var/"log/candela.log"
    error_log_path var/"log/candela.log"
  end

  test do
    system "#{bin}/candela", "version"
  end
end
