# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Candela < Formula
  desc "LLM observability proxy — traces, costs, budgets for AI dev tools"
  homepage "https://github.com/candelahq/candela"
  version "0.10.6"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/candelahq/candela/releases/download/v0.10.6/candela_0.10.6_Darwin_universal.tar.gz"
    sha256 "9047ca23ca5e253fbd5ebad79c5a941f718b7c52686c096ae4fd3d80843a6644"

    define_method(:install) do
      bin.install "candela"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/candelahq/candela/releases/download/v0.10.6/candela_0.10.6_Linux_amd64.tar.gz"
      sha256 "adac387bb4e480b50d91dd1612ea25a49a1df8cf0686ea06feabe80fa4c45e51"
      define_method(:install) do
        bin.install "candela"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/candelahq/candela/releases/download/v0.10.6/candela_0.10.6_Linux_arm64.tar.gz"
      sha256 "ca2e2464242b75fa310e7b731a003c7c677f1b152ecfce3fff179386b881d9a2"
      define_method(:install) do
        bin.install "candela"
      end
    end
  end

  def caveats
    <<~EOS
      To get started, create a config file:

        mkdir -p ~/.config/candela
        cat > ~/.config/candela/config.yaml <<EOF
        port: 8181
        providers:
          - name: google
            models: ["gemini-2.5-pro", "gemini-2.5-flash", "gemini-3.5-flash"]
          - name: anthropic
            models: ["claude-sonnet-4-20250514"]
        vertex_ai:
          project: YOUR_GCP_PROJECT
          region: us-central1
        EOF

      Authenticate (no gcloud required):
        candela auth login             # GCP OAuth2 (default)
        candela auth login --provider aws  # AWS SSO/access keys

      Then run:
        candela start          # background daemon
        candela status         # check running state
        candela run            # foreground (debug)

      Management UI: http://127.0.0.1:8181/_local/

      Or as a login service:
        brew services start candela
    EOS
  end

  service do
    run [opt_bin/"candela", "run"]
    keep_alive true
    log_path var/"log/candela.log"
    error_log_path var/"log/candela.log"
  end

  test do
    system "#{bin}/candela", "version"
  end
end
