# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Candela < Formula
  desc "LLM observability proxy — traces, costs, budgets for AI dev tools"
  homepage "https://github.com/candelahq/candela"
  version "0.10.5"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/candelahq/candela/releases/download/v0.10.5/candela_0.10.5_Darwin_universal.tar.gz"
    sha256 "6d12fd500652ac39e22553f09c4a4fecaae712b4d943fdb7f12c134968ab5c5e"

    define_method(:install) do
      bin.install "candela"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/candelahq/candela/releases/download/v0.10.5/candela_0.10.5_Linux_amd64.tar.gz"
      sha256 "02fd62653e774f96a2fdb6b2316d8bac0ac95b16eed148d29ff6d94aaa691a55"
      define_method(:install) do
        bin.install "candela"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/candelahq/candela/releases/download/v0.10.5/candela_0.10.5_Linux_arm64.tar.gz"
      sha256 "abad82e0f975873155a0e40e9c9d9ba65c13dc8cfa2fdc97e835e7eaad5ab98b"
      define_method(:install) do
        bin.install "candela"
      end
    end
  end

  def caveats
    <<~EOS
      To get started, create a config file:

        mkdir -p ~/.config/candela
        cat > ~/.config/candela/config.yaml <<EOF
        port: 8181
        providers:
          - name: google
            models: ["gemini-2.5-pro", "gemini-2.5-flash", "gemini-3.5-flash"]
          - name: anthropic
            models: ["claude-sonnet-4-20250514"]
        vertex_ai:
          project: YOUR_GCP_PROJECT
          region: us-central1
        EOF

      Authenticate (no gcloud required):
        candela auth login             # GCP OAuth2 (default)
        candela auth login --provider aws  # AWS SSO/access keys

      Then run:
        candela start          # background daemon
        candela status         # check running state
        candela run            # foreground (debug)

      Management UI: http://127.0.0.1:8181/_local/

      Or as a login service:
        brew services start candela
    EOS
  end

  service do
    run [opt_bin/"candela", "run"]
    keep_alive true
    log_path var/"log/candela.log"
    error_log_path var/"log/candela.log"
  end

  test do
    system "#{bin}/candela", "version"
  end
end
